// data.js
export const cafes = [
  "Diesel Cafe",
  "Whiteroom Deli",
  "USpizza",
  "The Coffee House",
  "Toast",
  "TLC Art Cafe",
  "Burger Lounge",
  "Knight Owl Cafe",
  "Lassi and Shakes",
  "Drood Cafe",
  "Brio Cafe",
  "It's Mangalore Cafe",
  "Big Bhudda Cafe",
  "Flames Cafe",
  "Cafe Flourista",
  "K9 Restro",
  "Kairos",
  "London Street",
  "Cloud Shisha",
  "Sizzler Ranch",
  "Hamburger",
  "Chocolate Confectionary",
  "Gossip Cafe",
  "Xara Restro Cafe",
  "Ziffy Cafe",
  "Tidbits",
  "Liquid The Cafe",
  "Waffle House",
  "Ideal Cafe",
  "The Mangalore Cafe",
  "The Kaffine Hub",
  "Tide The Coffee Shop",
  "Downtown Restro Shisha Cafe",
  "Oye Lassi Cafe Lounge",
  "Halo Garden",
  "Delhi Chat",
  "Ice Magic",
  "The Sailors Bistro",
  "X Cafe",
  "B Hub",
  "Basil Cafe",
  "Cafe Voila",
  "Olive Street Cafe",
  "The Juice (Alloysius)",
  "MHZ Gaming Cafe",
  "Belgian Waffle",
  "Cafe Coffee Day",
  "Cherry Square",
  "Buco",
  "Flow Car Drive In Cafe",
  "The Good Gelette",
  "Frozen Scoops Cafe",
  "Brott",
  "Ira The Fresh Kitchen",
  "Seasoning Cafe and Retro"
];

export const otherRestaurants = [
  "Juice Junction",
  "Big Fat Roll",
  "Swirliyo",
  "Kamath Condiments Car Street",
  "Dasanna Charmuri",
  "Kakunji Paratha",
  "KFC",
  "Dominos",
  "La Pinos",
  "Pizza Hut",
  "Mc Donald's",
  "Taco Bell",
  "Bamboo Restraunt",
  "Juice Dude",
  "Kulki Hub",
  "Shree Krishna Belpuri House",
  "Balli Shop Bonda Car Street"
];

export const breakfastPoints = [
  "Kadri Cafe",
  "Taj Mahal",
  "Dosa Camp",
  "The Narayana Cafe",
  "Moti Mahal",
  "Ideal Cafe",
  "Dosa Hut Ballabag",
  "Shivbagh Cafe",
  "Chettiar South Street",
  "Hotel Ayodhya"
];

export const fineDine = [
  "Asian Patio",
  "24 Karat",
  "Urban House",
  "Curry Wok",
  "Savoury",
  "Kobe Sizzlers",
  "Barbeque Nation",
  "Ocean Pearl",
  "Sai Palace",
  "Top House",
  "Liquid Lounge",
  "Onyx",
  "Punjabhi Dhabha",
  "Tandoori",
  "Hydrabad",
  "The Loft",
  "Estate Resort",
  "Madhuvan Village",
  "Spindrift",
  "Recycle Lounge",
  "Maharaja",
  "Chutney",
  "Shivsagar",
  "Ramponni",
  "Martins",
  "Chung Fa",
  "Hao Hao",
  "Hao Ming",
  "San Dige",
  "Kabab Studio",
  "Kudla Restraunt",
  "Shettys Lunch Home",
  "Cruise and Dine (Floating Restaurant)",
  "Kni Hao"
];

export const iceCreamDessert = [
  "Naturals Just Sundae",
  "Naturals Kadri",
  "Naturals Mango Berry",
  "Crave",
  "Mangalore Baking Company",
  "Swerliyo",
  "Keventers",
  "Waffle House",
  "Belgian Waffle",
  "Albatros",
  "Bonbons Cakes and Pastry",
  "Baskin Robin's",
  "Pabbas",
  "Polar Bear",
  "Stairway Bakery and Cafe",
  "Bombay Bakery",
  "Just Bakes",
  "Cakes and Bakes",
  "Brownie Point Mangalore",
  "Baklava Co",
  "Cherry Square",
  "Chocolate Confectionary",
  "Bonda Factory",
  "Donut Magic",
  "Vas Bakery",
  "Buco Artesisanal Cafe",
  "Sorbette",
  "Hive Ice Cream Parlor",
  "Cochin Bakery",
  "Crumbs",
  "Getaway Ice Cream and Dessert",
  "Cake My Day"
];

export const seafood = [
  "Machli",
  "Vanessa",
  "Shettys Lunch Home",
  "Kesari",
  "Macchis",
  "Unka Tinka"
];