package main

import (
	"database/sql"
	"log"
)

func SeedPlaces(db *sql.DB) {
	query := `
	INSERT INTO places (place_name, category) VALUES
	('Diesel Cafe','cafe'),
	('Whiteroom Deli','cafe'),
	('USpizza','cafe'),
	('The Coffee House','cafe'),
	('Toast','cafe'),
	('TLC Art Cafe','cafe'),
	('Burger Lounge','cafe'),
	('Knight Owl Cafe','cafe'),
	('Lassi and Shakes','cafe'),
	('Drood Cafe','cafe'),
	('Brio Cafe','cafe'),
	('It''s Mangalore Cafe','cafe'),
	('Big Bhudda Cafe','cafe'),
	('Flames Cafe','cafe'),
	('Cafe Flourista','cafe'),
	('K9 Restro','cafe'),
	('Kairos','cafe'),
	('London Street','cafe'),
	('Cloud Shisha','cafe'),
	('Sizzler Ranch','cafe'),
	('Hamburger','cafe'),
	('Chocolate Confectionary','cafe'),
	('Gossip Cafe','cafe'),
	('Xara Restro Cafe','cafe'),
	('Ziffy Cafe','cafe'),
	('Tidbits','cafe'),
	('Liquid The Cafe','cafe'),
	('Waffle House','cafe'),
	('Ideal Cafe','cafe'),
	('The Mangalore Cafe','cafe'),
	('The Kaffine Hub','cafe'),
	('Tide The Coffee Shop','cafe'),
	('Downtown Restro Shisha Cafe','cafe'),
	('Oye Lassi Cafe Lounge','cafe'),
	('Halo Garden','cafe'),
	('Delhi Chat','cafe'),
	('Ice Magic','cafe'),
	('The Sailors Bistro','cafe'),
	('X Cafe','cafe'),
	('B Hub','cafe'),
	('Basil Cafe','cafe'),
	('Cafe Voila','cafe'),
	('Olive Street Cafe','cafe'),
	('The Juice (Alloysius)','cafe'),
	('MHZ Gaming Cafe','cafe'),
	('Belgian Waffle','cafe'),
	('Cafe Coffee Day','cafe'),
	('Cherry Square','cafe'),
	('Buco','cafe'),
	('Flow Car Drive In Cafe','cafe'),
	('The Good Gelette','cafe'),
	('Frozen Scoops Cafe','cafe'),
	('Brott','cafe'),
	('Ira The Fresh Kitchen','cafe'),
	('Seasoning Cafe and Retro','cafe'),

	('Juice Junction','other'),
	('Big Fat Roll','other'),
	('Swirliyo','other'),
	('Kamath Condiments Car Street','other'),
	('Dasanna Charmuri','other'),
	('Kakunji Paratha','other'),
	('KFC','other'),
	('Dominos','other'),
	('La Pinos','other'),
	('Pizza Hut','other'),
	('Mc Donald''s','other'),
	('Taco Bell','other'),
	('Bamboo Restraunt','other'),
	('Juice Dude','other'),
	('Kulki Hub','other'),
	('Shree Krishna Belpuri House','other'),
	('Balli Shop Bonda Car Street','other'),

	('Kadri Cafe','breakfast'),
	('Taj Mahal','breakfast'),
	('Dosa Camp','breakfast'),
	('The Narayana Cafe','breakfast'),
	('Moti Mahal','breakfast'),
	('Ideal Cafe','breakfast'),
	('Dosa Hut Ballabag','breakfast'),
	('Shivbagh Cafe','breakfast'),
	('Chettiar South Street','breakfast'),
	('Hotel Ayodhya','breakfast'),

	('Asian Patio','finedine'),
	('24 Karat','finedine'),
	('Urban House','finedine'),
	('Curry Wok','finedine'),
	('Savoury','finedine'),
	('Kobe Sizzlers','finedine'),
	('Barbeque Nation','finedine'),
	('Ocean Pearl','finedine'),
	('Sai Palace','finedine'),
	('Top House','finedine'),
	('Liquid Lounge','finedine'),
	('Onyx','finedine'),
	('Punjabhi Dhabha','finedine'),
	('Tandoori','finedine'),
	('Hydrabad','finedine'),
	('The Loft','finedine'),
	('Estate Resort','finedine'),
	('Madhuvan Village','finedine'),
	('Spindrift','finedine'),
	('Recycle Lounge','finedine'),
	('Maharaja','finedine'),
	('Chutney','finedine'),
	('Shivsagar','finedine'),
	('Ramponni','finedine'),
	('Martins','finedine'),
	('Chung Fa','finedine'),
	('Hao Hao','finedine'),
	('Hao Ming','finedine'),
	('San Dige','finedine'),
	('Kabab Studio','finedine'),
	('Kudla Restraunt','finedine'),
	('Shettys Lunch Home','finedine'),
	('Cruise and Dine (Floating Restaurant)','finedine'),
	('Kni Hao','finedine'),

	('Naturals Just Sundae','icecream'),
	('Naturals Kadri','icecream'),
	('Naturals Mango Berry','icecream'),
	('Crave','icecream'),
	('Mangalore Baking Company','icecream'),
	('Swerliyo','icecream'),
	('Keventers','icecream'),
	('Waffle House','icecream'),
	('Belgian Waffle','icecream'),
	('Albatros','icecream'),
	('Bonbons Cakes and Pastry','icecream'),
	('Baskin Robin''s','icecream'),
	('Pabbas','icecream'),
	('Polar Bear','icecream'),
	('Stairway Bakery and Cafe','icecream'),
	('Bombay Bakery','icecream'),
	('Just Bakes','icecream'),
	('Cakes and Bakes','icecream'),
	('Brownie Point Mangalore','icecream'),
	('Baklava Co','icecream'),
	('Cherry Square','icecream'),
	('Chocolate Confectionary','icecream'),
	('Bonda Factory','icecream'),
	('Donut Magic','icecream'),
	('Vas Bakery','icecream'),
	('Buco Artesisanal Cafe','icecream'),
	('Sorbette','icecream'),
	('Hive Ice Cream Parlor','icecream'),
	('Cochin Bakery','icecream'),
	('Crumbs','icecream'),
	('Getaway Ice Cream and Dessert','icecream'),
	('Cake My Day','icecream'),

	('Machli','seafood'),
	('Vanessa','seafood'),
	('Shettys Lunch Home','seafood'),
	('Kesari','seafood'),
	('Macchis','seafood'),
	('Unka Tinka','seafood');
	`

	_, err := db.Exec(query)
	if err != nil {
		log.Println("❌ Seeding failed:", err)
		return
	}

	log.Println("✅ Data seeded successfully!")
}